Repository GSG-G13/ecommerce-team5, pull requests merged in 2023-05, with the labels that each got.

#2 add the file structure and install necessary packages
  server/.gitignore
  server/controller/index.js
  server/controller/test.js
  server/database/index.js
  server/package-lock.json
  server/package.json
  server/router/index.js
Labels: waiting-review, done

#4 fix some set up issues
  client/package.json
  package.json
  server/.eslintrc.json
  server/package-lock.json
  server/package.json
Labels: waiting-review

#8 remove unused files from client
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/components/index.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/reportWebVitals.js
  client/src/setupTests.js
Labels: waiting-review

#11 craeted and connected the db and creted a router file
  server/app.js
  server/controller/singup.js
  server/database/config/build.js
  server/database/config/build.sql
  server/database/config/connection.js
  server/database/index.js
  server/router/index.js
Labels: waiting-review

#12 add navbar and footer
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/public/images/logo-image.svg
  client/src/App.css
  client/src/App.js
  client/src/components/Footer/index.jsx
  client/src/components/Footer/style.css
  client/src/components/HeaderWithFooter/index.jsx
  client/src/components/Navbar/index.jsx
  client/src/components/Navbar/style.css
  client/src/components/index.js
  client/src/index.js
  client/src/router/index.js
Labels: waiting-review

#14 edit router structure
  client/src/router/index.js
Labels: waiting-review

#15 cont Home Page
  client/src/App.js
  client/src/components/HomeContent/index.jsx
  client/src/components/HomePage/index.jsx
  client/src/router/index.js
Labels: done

#17 handle login button
  client/src/components/Navbar/index.jsx
Labels: waiting-review

#18 11 create Sing Up component
  client/.eslintrc.json
  client/public/images/shopping.svg
  client/src/App.js
  client/src/components/singuppage/index.jsx
  client/src/components/singuppage/style.css
  client/src/router/index.js
  server/controller/singup.js
Labels: waiting-review

#23 added the logic and front-end validation of the sign up form
  client/src/components/singuppage/index.jsx
  client/src/components/singuppage/style.css
Labels: waiting-review

#27 merge battrawi codes and some signup page fixes
  client/src/components/CategoryFilter/index.jsx
  client/src/components/HomeContent/index.jsx
  client/src/components/singuppage/index.jsx
Labels: done

#28 fix-filters
  client/src/App.css
  client/src/components/CategoryFilter/index.jsx
  client/src/components/HomeContent/index.jsx
Labels: waiting-review

#29 26 create login page
  client/src/components/loginpage/index.jsx
  client/src/components/loginpage/style.css
  client/src/router/index.js
  server/router/index.js
Labels: done

#32 cart page and some fixes
  client/src/App.css
  client/src/components/Cart/index.jsx
  client/src/components/CategoryFilter/index.jsx
  client/src/components/Footer/index.jsx
  client/src/components/Navbar/index.jsx
  client/src/router/index.js
Labels: waiting-review

#33 fix some issues in the file
  client/src/components/singuppage/index.jsx
Labels: done

#37 link shop now link to login page
  client/src/components/HomeContent/index.jsx
Labels: waiting-review

#35 finalize the login and signup pages with validation
  client/src/components/loginpage/index.jsx
  client/src/components/singuppage/index.jsx
  server/router/index.js
Labels: waiting-review

#41 handle queries and conrolter and routes for the cart in the server an…
  server/controller/getcarthandler.js
  server/controller/getproductshandler.js
  server/database/config/connection.js
  server/database/queries/getcartquery.js
  server/database/queries/getproductsquery.js
  server/router/index.js
Labels: waiting-review

#43 fix updta.sql and crate fakedata.sql files to genttate fake data
  client/src/components/singuppage/index.jsx
  server/controller/login.js
  server/database/config/build.sql
  server/database/config/fakeData.sql
  server/database/queries/loginquery.js
  server/database/queries/singupquery.js
Labels: waiting-review

#49 single product page & products filters done
  client/src/components/CategoryFilter/index.jsx
  client/src/components/Footer/index.jsx
  client/src/components/HomeContent/Product.jsx
  client/src/components/HomeContent/index.jsx
  client/src/components/ProductPage/index.jsx
  client/src/components/singuppage/index.jsx
Labels: waiting-review

#50 push server edits
  server/controller/getCategoryController.js
  server/controller/getFilteredProductsController.js
  server/controller/getSingleProductController.js
  server/controller/getproductshandler.js
  server/database/config/build.js
  server/database/config/connection.js
  server/database/config/fakeData.sql
  server/database/queries/getCategories.js
  server/database/queries/getFilteredProducts.js
  server/database/queries/getcartquery.js
  server/database/queries/getproductsquery.js
  server/database/queries/gitSingleProduct.js
  server/router/index.js
Labels: waiting-review

#52 some fixes
  server/controller/cart/getCart.js
  server/database/queries/cart/getCart.js
  server/router/index.js
Labels: waiting-review
